### PR TITLE
Remove Trace.WriteLine calls to avoid deadlocks

### LINKED ISSUE #996: GitHub extension causes VS to hang on startup
@shana 
A customer reported that Visual Studio hangs on startup and provided dumps.

[https://developercommunity.visualstudio.com/storage/attachments/5786-memory-14860-1494611473196.dmp
](https://developercommunity.visualstudio.com/storage/attachments/5786-memory-14860-1494611473196.dmp
)
>	ntdll.dll!_NtWaitForMultipleObjects@20()	Unknown
 	KERNELBASE.dll!WaitForMultipleObjectsEx(unsigned long nCount, void * const * lpHandles, int bWaitAll, unsigned long dwMilliseconds, int bAlertable) Line 1551	C
 	WindowsBase.ni.dll!6268bb14()	Unknown
 	[Frames below may be incorrect and/or missing, native debugger attempting to walk managed call stack]	
 	WindowsBase.ni.dll!6268bb14()	Unknown
 	[Managed to Native Transition]	
 	WindowsBase.dll!MS.Win32.UnsafeNativeMethods.WaitForMultipleObjectsEx(int nCount, System.IntPtr[] pHandles, bool bWaitAll, int dwMilliseconds, bool bAlertable)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherSynchronizationContext.Wait(System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout)	Unknown
 	mscorlib.dll!System.Threading.SynchronizationContext.InvokeWaitMethodHelper(System.Threading.SynchronizationContext syncContext, System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.dll!System.Diagnostics.TraceInternal.WriteLine(string message)	Unknown
 	GitHub.VisualStudio.dll!GitHub.VisualStudio.AssemblyResolverPackage.LoadAssemblyFromExtensionDir(object sender, System.ResolveEventArgs e)	Unknown
 	mscorlib.dll!System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly assembly, string assemblyFullName)	Unknown
 	[Native to Managed Transition]	
 	mscorlib.ni.dll!70a33005()	Unknown
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Reflection.RuntimeAssembly.nLoad(System.Reflection.AssemblyName fileName, string codeBase, System.Security.Policy.Evidence assemblySecurity, System.Reflection.RuntimeAssembly locationHint, ref System.Threading.StackCrawlMark stackMark, System.IntPtr pPrivHostBinder, bool throwOnFileNotFound, bool forIntrospection, bool suppressSecurityChecks)	Unknown
 	mscorlib.dll!System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName assemblyRef, System.Security.Policy.Evidence assemblySecurity, System.Reflection.RuntimeAssembly reqAssembly, ref System.Threading.StackCrawlMark stackMark, System.IntPtr pPrivHostBinder, bool throwOnFileNotFound, bool forIntrospection, bool suppressSecurityChecks)	Unknown
 	mscorlib.dll!System.Reflection.RuntimeAssembly.InternalLoad(string assemblyString, System.Security.Policy.Evidence assemblySecurity, ref System.Threading.StackCrawlMark stackMark, System.IntPtr pPrivHostBinder, bool forIntrospection)	Unknown
 	mscorlib.dll!System.Reflection.RuntimeAssembly.InternalLoad(string assemblyString, System.Security.Policy.Evidence assemblySecurity, ref System.Threading.StackCrawlMark stackMark, bool forIntrospection)	Unknown
 	mscorlib.dll!System.Reflection.Assembly.Load(string assemblyString)	Unknown
 	PresentationFramework.dll!System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(System.Windows.Baml2006.Baml2006SchemaContext.BamlAssembly bamlAssembly)	Unknown
 	PresentationFramework.dll!System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(System.Windows.Baml2006.Baml2006SchemaContext.BamlType bamlType)	Unknown
 	PresentationFramework.dll!System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(System.Windows.Baml2006.Baml2006SchemaContext.BamlType bamlType, short typeId)	Unknown
 	PresentationFramework.dll!System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(short typeId)	Unknown
 	PresentationFramework.dll!System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()	Unknown
 	PresentationFramework.dll!System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()	Unknown
 	PresentationFramework.dll!System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()	Unknown
 	PresentationFramework.dll!System.Windows.Baml2006.Baml2006Reader.Read()	Unknown
 	PresentationFramework.dll!System.Windows.Markup.WpfXamlLoader.TransformNodes(System.Xaml.XamlReader xamlReader, System.Xaml.XamlObjectWriter xamlWriter, bool onlyLoadOneNode, bool skipJournaledProperties, bool shouldPassLineNumberInfo, System.Xaml.IXamlLineInfo xamlLineInfo, System.Xaml.IXamlLineInfoConsumer xamlLineInfoConsumer, MS.Internal.Xaml.Context.XamlContextStack<System.Windows.Markup.WpfXamlFrame> stack, System.Windows.Markup.IStyleConnector styleConnector)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader xamlReader, System.Xaml.IXamlObjectWriterFactory writerFactory, bool skipJournaledProperties, object rootObject, System.Xaml.XamlObjectWriterSettings settings, System.Uri baseUri)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader xamlReader, bool skipJournaledProperties, object rootObject, System.Xaml.Permissions.XamlAccessLevel accessLevel, System.Uri baseUri)	Unknown
 	PresentationFramework.dll!System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream stream, System.Windows.Markup.ParserContext parserContext, object parent, bool closeStream)	Unknown
 	PresentationFramework.dll!System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream stream, System.Windows.Markup.ParserContext pc)	Unknown
 	PresentationFramework.dll!System.Windows.Application.LoadComponent(System.Uri resourceLocator, bool bSkipJournaledProperties)	Unknown
 	PresentationFramework.dll!System.Windows.Application.LoadComponent(System.Uri resourceLocator)	Unknown
 	Microsoft.VisualStudio.Imaging.dll!Microsoft.VisualStudio.Imaging.UriSourceDescriptor.LoadManagedImage(Microsoft.VisualStudio.Utilities.Int16Size deviceSize) Line 117	C#
 	Microsoft.VisualStudio.Imaging.dll!Microsoft.VisualStudio.Imaging.SourceDescriptor.LoadImage(Microsoft.VisualStudio.Imaging.ImageMoniker moniker, Microsoft.VisualStudio.Imaging.ImageAttributes attributes, bool canTheme, bool debugMode, System.Windows.Media.Color debugColor) Line 417	C#
 	Microsoft.VisualStudio.Imaging.dll!Microsoft.VisualStudio.Imaging.SingleImageBundle.RealizeNativeFormatResource(Microsoft.VisualStudio.Imaging.ImageLibrary library, Microsoft.VisualStudio.Imaging.ImageAttributes attributes) Line 281	C#
 	Microsoft.VisualStudio.Imaging.dll!Microsoft.VisualStudio.Imaging.ResourceBundle.GetResourceCore(Microsoft.VisualStudio.Imaging.ImageLibrary library, Microsoft.VisualStudio.Imaging.ImageAttributes desiredAttributes, Microsoft.VisualStudio.Imaging.ImageFormat nativeFormat, Microsoft.VisualStudio.Imaging.ImageKind nativeKind) Line 260	C#
 	Microsoft.VisualStudio.Imaging.dll!Microsoft.VisualStudio.Imaging.ImageBundle.GetImage(Microsoft.VisualStudio.Imaging.ImageLibrary library, Microsoft.VisualStudio.Imaging.ImageAttributes attributes) Line 72	C#
 	Microsoft.VisualStudio.Imaging.dll!Microsoft.VisualStudio.Imaging.ImageLibrary.GetImageCore<Microsoft.VisualStudio.Imaging.ImageBundle>(Microsoft.VisualStudio.Imaging.ImageMoniker moniker, Microsoft.VisualStudio.Imaging.ImageAttributes attributes, int beginCodeMarker, int endCodeMarker, string imageType, Microsoft.VisualStudio.Imaging.IBundleCollection<Microsoft.VisualStudio.Imaging.ImageBundle>[] collections) Line 768	C#
 	Microsoft.VisualStudio.Imaging.dll!Microsoft.VisualStudio.Imaging.ImageLibrary.GetImage(Microsoft.VisualStudio.Imaging.ImageMoniker moniker, Microsoft.VisualStudio.Imaging.ImageAttributes attributes) Line 718	C#
 	Microsoft.VisualStudio.Imaging.dll!Microsoft.VisualStudio.Imaging.CrispImageSourceConverter.ConvertCore(Microsoft.VisualStudio.Imaging.ImageLibrary library, Microsoft.VisualStudio.Imaging.ImageMoniker moniker, double logicalWidth, double logicalHeight, System.Windows.Media.Color background, bool grayscale, System.Windows.Media.Color biasColor, bool highContrast, double dpi, double scaleFactor) Line 64	C#
 	Microsoft.VisualStudio.Imaging.dll!Microsoft.VisualStudio.Imaging.CrispImageSourceConverter.Convert(Microsoft.VisualStudio.Imaging.ImageLibrary library, Microsoft.VisualStudio.Imaging.ImageMoniker moniker, double logicalWidth, double logicalHeight, System.Windows.Media.Color background, bool grayscale, System.Windows.Media.Color biasColor, bool highContrast, double dpi, double scaleFactor, bool isLibraryInitialized, object parameter, System.Globalization.CultureInfo culture) Line 25	C#
 	Microsoft.VisualStudio.Utilities.dll!Microsoft.VisualStudio.PlatformUI.MultiValueConverter<Microsoft.VisualStudio.Imaging.ImageLibrary, Microsoft.VisualStudio.Imaging.ImageMoniker, double, double, System.Windows.Media.Color, bool, System.Windows.Media.Color, bool, double, double, bool, System.Windows.Media.ImageSource>.Convert(object[] values, System.Type targetType, object parameter, System.Globalization.CultureInfo culture) Line 651	C#
 	PresentationFramework.dll!System.Windows.Data.MultiBindingExpression.TransferValue()	Unknown
 	PresentationFramework.dll!System.Windows.Data.MultiBindingExpression.Transfer()	Unknown
 	PresentationFramework.dll!System.Windows.Data.MultiBindingExpression.UpdateTarget(bool includeInnerBindings)	Unknown
 	PresentationFramework.dll!System.Windows.Data.MultiBindingExpression.AttachToContext(bool lastChance)	Unknown
 	PresentationFramework.dll!System.Windows.Data.MultiBindingExpression.AttachOverride(System.Windows.DependencyObject d, System.Windows.DependencyProperty dp)	Unknown
 	PresentationFramework.dll!System.Windows.Data.BindingExpressionBase.OnAttach(System.Windows.DependencyObject d, System.Windows.DependencyProperty dp)	Unknown
 	PresentationFramework.dll!System.Windows.StyleHelper.GetInstanceValue(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]> dataField, System.Windows.DependencyObject container, System.Windows.FrameworkElement feChild, System.Windows.FrameworkContentElement fceChild, int childIndex, System.Windows.DependencyProperty dp, int i, ref System.Windows.EffectiveValueEntry entry)	Unknown
 	PresentationFramework.dll!System.Windows.StyleHelper.GetChildValueHelper(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]> dataField, ref MS.Utility.ItemStructList<System.Windows.ChildValueLookup> valueLookupList, System.Windows.DependencyProperty dp, System.Windows.DependencyObject container, MS.Internal.FrameworkObject child, int childIndex, bool styleLookup, ref System.Windows.EffectiveValueEntry entry, out System.Windows.ValueLookupType sourceType, System.Windows.FrameworkElementFactory templateRoot)	Unknown
 	PresentationFramework.dll!System.Windows.StyleHelper.GetChildValue(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]> dataField, System.Windows.DependencyObject container, int childIndex, MS.Internal.FrameworkObject child, System.Windows.DependencyProperty dp, ref MS.Utility.FrugalStructList<System.Windows.ChildRecord> childRecordFromChildIndex, ref System.Windows.EffectiveValueEntry entry, out System.Windows.ValueLookupType sourceType, System.Windows.FrameworkElementFactory templateRoot)	Unknown
 	PresentationFramework.dll!System.Windows.StyleHelper.GetValueFromStyleOrTemplate(MS.Internal.FrameworkObject fo, System.Windows.DependencyProperty dp, ref System.Windows.EffectiveValueEntry entry)	Unknown
 	PresentationFramework.dll!System.Windows.StyleHelper.ApplyStyleOrTemplateValue(MS.Internal.FrameworkObject fo, System.Windows.DependencyProperty dp)	Unknown
 	PresentationFramework.dll!System.Windows.StyleHelper.InvalidateContainerDependents(System.Windows.DependencyObject container, ref MS.Utility.FrugalStructList<System.Windows.ContainerDependent> exclusionContainerDependents, ref MS.Utility.FrugalStructList<System.Windows.ContainerDependent> oldContainerDependents, ref MS.Utility.FrugalStructList<System.Windows.ContainerDependent> newContainerDependents)	Unknown
 	PresentationFramework.dll!System.Windows.StyleHelper.DoThemeStyleInvalidations(System.Windows.FrameworkElement fe, System.Windows.FrameworkContentElement fce, System.Windows.Style oldThemeStyle, System.Windows.Style newThemeStyle, System.Windows.Style style)	Unknown
 	PresentationFramework.dll!System.Windows.StyleHelper.UpdateThemeStyleCache(System.Windows.FrameworkElement fe, System.Windows.FrameworkContentElement fce, System.Windows.Style oldThemeStyle, System.Windows.Style newThemeStyle, ref System.Windows.Style themeStyleCache)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnThemeStyleChanged(System.Windows.DependencyObject d, object oldValue, object newValue)	Unknown
 	PresentationFramework.dll!System.Windows.StyleHelper.GetThemeStyle(System.Windows.FrameworkElement fe, System.Windows.FrameworkContentElement fce)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.UpdateThemeStyleProperty()	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.OnInitialized(System.EventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.TryFireInitialized()	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.EndInit()	Unknown
 	System.Xaml.dll!MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(System.Xaml.XamlType xamlType, object obj, bool begin)	Unknown
 	System.Xaml.dll!MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.InitializationGuard(System.Xaml.XamlType xamlType, object obj, bool begin)	Unknown
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.Logic_EndInit(MS.Internal.Xaml.Context.ObjectWriterContext ctx)	Unknown
 	System.Xaml.dll!System.Xaml.XamlObjectWriter.WriteEndObject()	Unknown
 	System.Xaml.dll!System.Xaml.XamlWriter.WriteNode(System.Xaml.XamlReader reader)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlReader templateReader, System.Xaml.XamlObjectWriter currentWriter)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.LoadTemplateXaml(System.Xaml.XamlObjectWriter objectWriter)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(System.Windows.DependencyObject container, System.Windows.Markup.IComponentConnector componentConnector, System.Windows.Markup.IStyleConnector styleConnector, System.Collections.Generic.List<System.Windows.DependencyObject> affectedChildren, System.Windows.UncommonField<System.Collections.Hashtable> templatedNonFeChildrenField)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.LoadContent(System.Windows.DependencyObject container, System.Collections.Generic.List<System.Windows.DependencyObject> affectedChildren)	Unknown
 	PresentationFramework.dll!System.Windows.StyleHelper.ApplyTemplateContent(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]> dataField, System.Windows.DependencyObject container, System.Windows.FrameworkElementFactory templateRoot, int lastChildIndex, System.Collections.Specialized.HybridDictionary childIndexFromChildID, System.Windows.FrameworkTemplate frameworkTemplate)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkTemplate.ApplyTemplateContent(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]> templateDataField, System.Windows.FrameworkElement container)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.ApplyTemplate()	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize)	Unknown
 	PresentationFramework.dll!MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement element, System.Windows.Size constraint)	Unknown
 	PresentationFramework.dll!System.Windows.Controls.ContentPresenter.MeasureOverride(System.Windows.Size constraint)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize)	Unknown
 	PresentationFramework.dll!System.Windows.Controls.StackPanel.StackMeasureHelper(System.Windows.Controls.IStackMeasure measureElement, System.Windows.Controls.IStackMeasureScrollData scrollData, System.Windows.Size constraint)	Unknown
 	PresentationFramework.dll!System.Windows.Controls.StackPanel.MeasureOverride(System.Windows.Size constraint)	Unknown
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize)	Unknown
 	PresentationCore.dll!System.Windows.ContextLayoutManager.UpdateLayout()	Unknown
 	PresentationCore.dll!System.Windows.ContextLayoutManager.UpdateLayoutCallback(object arg)	Unknown
 	PresentationCore.dll!System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()	Unknown
 	PresentationCore.dll!System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()	Unknown
 	PresentationCore.dll!System.Windows.Media.MediaContext.RenderMessageHandlerCore(object resizedCompositionTarget)	Unknown
 	PresentationCore.dll!System.Windows.Media.MediaContext.RenderMessageHandler(object resizedCompositionTarget)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)	Unknown
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
 	[Native to Managed Transition]	
 	user32.dll!__InternalCallWinProc@20()	Unknown
 	user32.dll!_UserCallWinProcCheckWow@36()	Unknown
 	user32.dll!_DispatchMessageWorker@8()	Unknown
 	user32.dll!_DispatchMessageW@4()	Unknown
 	msenv.dll!MainMessageLoop::ProcessMessage(IMsoStdComponentMgr * pstdcm, IVsWindowManager * pIVsWindowManager, tagMSG & msg) Line 1708	C++
 	msenv.dll!CMsoCMHandler::EnvironmentMsgLoop() Line 450	C++
 	msenv.dll!CMsoCMHandler::FPushMessageLoop(unsigned long uReason) Line 358	C++
 	msenv.dll!SCM::FPushMessageLoop(SCMI * pscmi, unsigned long uReason, void * pvLoopData) Line 2262	C++
 	msenv.dll!SCM_MsoCompMgr::FPushMessageLoop(unsigned long dwComponentID, unsigned long uReason, void * pvLoopData) Line 2998	C++
 	msenv.dll!CMsoComponent::PushMsgLoop(unsigned long msgloop) Line 705	C++
 	msenv.dll!VStudioMainLogged() Line 1365	C++
 	msenv.dll!VStudioMain(MAINPARAM * pMainParam) Line 1446	C++
 	devenv.exe!util_CallVsMain(MAINPARAM * pMainParam, int * piRes) Line 1088	C++
 	devenv.exe!CDevEnvAppId::Run(wchar_t * wszCmdLine, int nCmdShow) Line 855	C++
 	devenv.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, char * lpCmdLine, int nCmdShow) Line 71	C++
 	[Inline Frame] devenv.exe!invoke_main() Line 94	C++
 	devenv.exe!__scrt_common_main_seh() Line 259	C++
 	kernel32.dll!BaseThreadInitThunk(unsigned long RunProcessInit, long(__stdcall*)(void *) StartAddress, void * Argument) Line 64	C
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown

### PR DESCRIPTION
**Pull request by shana**
I know we're moving away from this, but still, while it's around, make sure it doesn't deadlock if we have to re-enable it.

Fixes #996

### CODE REVIEW

File: src/GitHub.VisualStudio/AssemblyResolverPackage.cs [hunk 1]
```diff
@@ -35,7 +35,6 @@ public class AssemblyResolverPackage : Package
 
         public AssemblyResolverPackage()
         {
-            Debug.WriteLine("GitHub assembly resolver is now active.");
             extensionDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
             AppDomain.CurrentDomain.AssemblyResolve += LoadAssemblyFromExtensionDir;
```
Comment (jcansdale) [inline src/GitHub.VisualStudio/AssemblyResolverPackage.cs]: The two `ProvideAutoLoad` lines are commented out so this package should never get loaded.

I've only left it here in case we're using an "Experimental" version on top of an old "AllUsers" version. Otherwise the "AllUsers" package might be visible behind the now missing "Experimental" package.

It would make sense to empty out this package completely and only leave an empty stub (that would generally not get loaded). If this unusual situation does happen it can be really confusing with assemblies from different versions loaded.

P.S. I'm testing inline comments on the `Debug` line. ;-)

Comment (jcansdale) [inline src/GitHub.VisualStudio/AssemblyResolverPackage.cs]: Another attempt at adding comment to `Debug` line.

File: src/GitHub.VisualStudio/AssemblyResolverPackage.cs [hunk 2]
```diff
@@ -35,7 +35,6 @@ public class AssemblyResolverPackage : Package
 
         public AssemblyResolverPackage()
         {
-            Debug.WriteLine("GitHub assembly resolver is now active.");
             extensionDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
```
Comment (jcansdale) [inline src/GitHub.VisualStudio/AssemblyResolverPackage.cs]: diff line 4
