### PR TITLE
Ignore inline comment if it contains no diff line context

### LINKED ISSUE #1435: Sometimes inline comments have no associated diff lines
- GitHub Extension for Visual Studio version: 2.4.0 (dev)
- Visual Studio version: 2015

__What happened__ (with steps, logs and screenshots, if possible)

An exception was thrown on this line:
https://github.com/github/VisualStudio/blob/975816ed6520e74774cf456e749cd435a4c830ef/src/GitHub.InlineReviews/Models/InlineCommentThreadModel.cs#L54

This is the inline comment that has no diff line context: https://github.com/grokys/PullRequestSandbox/pull/24#pullrequestreview-41516276

```
    Body: "comment on main"
    CommitId: "080d67f93efeb557f8bb24a009effb85bde353aa"
    CreatedAt: {01/06/2017 13:55:49 +00:00}
    DiffHunk: "@@ -10,7 +10,6 @@ class Program"
    Id: 119620146
    OriginalCommitId: "b328e39e53c85ea15208a60c7af74698d3e146d2"
    OriginalPosition: 6
    Path: "PullRequestSandbox/Program.cs"
    Position: 0
    User: Account: Login: jcansdale IsUser: True
```

### PR DESCRIPTION
**Pull request by jcansdale**
It's possible (if unlikely) that an inline comment contains no diff line context. For example, the following comment has no context:

grokys/PullRequestSandbox#24

```
    Body: "comment on main"
    CommitId: "080d67f93efeb557f8bb24a009effb85bde353aa"
    CreatedAt: {01/06/2017 13:55:49 +00:00}
    DiffHunk: "@@ -10,7 +10,6 @@ class Program"
    Id: 119620146
    OriginalCommitId: "b328e39e53c85ea15208a60c7af74698d3e146d2"
    OriginalPosition: 6
    Path: "PullRequestSandbox/Program.cs"
    Position: 0
    User: Account: Login: jcansdale IsUser: True
```

This was caused a comment with a `Position` of `0` (it should be 1 or above). Diff file line numbers are `1` based, so this comment is outside the bounds of the diff. Although this wouldn't normally happen, there is a comment like this in `PullRequestSandbox` that would be hit from time to time when testing.

This PR simply ignores and logs comment like this.

Fixes #1435

### CODE REVIEW

File: src/GitHub.InlineReviews/Services/PullRequestSessionService.cs [hunk 1]
```diff
@@ -88,11 +92,20 @@ public class PullRequestSessionService : IPullRequestSessionService
...
+                    continue;
+                }
+
+                var diffLineType = firstLine.Type;
                 var thread = new InlineCommentThreadModel(
                     relativePath,
                     comments.Key.Item1,
                     comments.Key.Item2,
                     diffLines,
+                    diffLineType,
```
Comment (grokys) [inline src/GitHub.InlineReviews/Services/PullRequestSessionService.cs]: Do we need to pass `diffLineType` into the ctor separately, considering that at this point `firstLine != null`?

Comment (jcansdale) [reply src/GitHub.InlineReviews/Services/PullRequestSessionService.cs]: I thought since we need to check for this situation anyway and have the data, we may as well pass it in. Keeps it a little simpler. What are the cons?

Comment (grokys) [reply src/GitHub.InlineReviews/Services/PullRequestSessionService.cs]: Just duplicated information really - it makes the API less fault tolerant, because you can pass in a `diffLineType != diffLines[0]` and doing a `First()` on `diffLines` isn't going to be expensive. That's my feeling at least. Feel free to disagree though and I'll 👍.

Comment (jcansdale) [reply src/GitHub.InlineReviews/Services/PullRequestSessionService.cs]: Makes sense. I didn't like `DiffLineType` failing when it came to be used, but there's no reason not to populate this in the constructor.
