### PR TITLE
Fix ObjectDisposedException crash when loading PRs

### LINKED ISSUE #505: Clicking Pull Requests button in GitHub pane causes `ObjectDisposedException`
On current master, if I have the GitHub pane open and click the "Pull Requests" button I get:

```
System.ObjectDisposedException occurred
  HResult=-2146232798
  Message=Cannot access a disposed object.
  ObjectName=""
  Source=System.Reactive.Linq
  StackTrace:
       at System.Reactive.Subjects.ReplaySubject`1.ReplayBufferBase.CheckDisposed()
       at System.Reactive.Subjects.ReplaySubject`1.ReplayBufferBase.OnCompleted()
       at System.Reactive.Subjects.ReplaySubject`1.OnCompleted()
       at GitHub.Collections.TrackingCollection`1.<Listen>b__36_2() in D:\projects\VisualStudio\src\GitHub.Exports.Reactive\Collections\TrackingCollection.cs:line 303
  InnerException: 
```

It doesn't happen every time. If it doesn't, close the pane and try again, or try restarting VS. After a few tries it should throw.

### PR DESCRIPTION
**Pull request by shana**
Fixes #505

### CODE REVIEW

File: src/TrackingCollectionTests/TrackingCollectionTests.cs [hunk 1]
```diff
@@ -1797,25 +1798,43 @@ public void Removing()
...
+            GetThing(6, 6),
+            GetThing(7, 7),
+            GetThing(8, 8),
+            GetThing(9, 9),
+            GetThing(10, 10),
+        });
+
+        col.Filter = null;
+
+        expectedCount = 15;
```
Comment (grokys) [inline src/TrackingCollectionTests/TrackingCollectionTests.cs]: This unit test is getting rather long - might it be best to split this test out into a separate test method?
