### PR TITLE
Fix opening links on enterprise instances.

### LINKED ISSUE #1291: No Open/Link to GitHub Available
- GitHub Extension for Visual Studio  version: 2.3.4.54
- Visual Studio version: 15.4.2

**Repro**:
1. Open solution that is in a git repo from our GitHub Enterprise.
2. Open any code (.cs) file (or .config, for instance).
3. Right-click on any line to view the context menu.

**Expected**: See a GitHub -> menu that has an Open/Link to GitHub link that will take me to the corresponding line in the repo/branch that I'm on at the time.

**Actual**: No GitHub menu. 

**Notes**: I reported this to Phil Haack and he looped in Andreia Gaita on Twitter. She suggested I report this here. 

Will email logs.

### PR DESCRIPTION
**Pull request by grokys**
Correctly compare repository full name.

Previously we were comparing `repo.FullName == ActiveRepo.Name` which always failed as `repo.FullName` returns `owner/name` whereas `ActiveRepo.Name` just returns the `name` portion. Construct a full name for the active repo and check that.

Fixes #1291

### CODE REVIEW

File: src/GitHub.VisualStudio/Menus/MenuBase.cs [hunk 1]
```diff
@@ -131,7 +131,8 @@ void RefreshRepo()
             if (!isdotcom)
             {
                 var repo = await SimpleApiClient.GetRepository();
-                return (repo.FullName == ActiveRepo.Name || repo.Id == 0) && SimpleApiClient.IsEnterprise();
+                var activeRepoFullName = ActiveRepo.Owner + '/' + ActiveRepo.Name;
+                return (repo.FullName == activeRepoFullName || repo.Id == 0) && SimpleApiClient.IsEnterprise();
```
Comment (grokys) [inline src/GitHub.VisualStudio/Menus/MenuBase.cs]: I'm not sure what the check for `repo.Id == 0` does here?

**Comment by meaghanlewis** [comment]
This LGTM 👍 . Thanks for the fix @grokys
